### PR TITLE
refactor: use a standalone logger module instead of attaching it to `global` 

### PR DESCRIPTION
**Pull request by cijiugechu**

### CODE REVIEW

**Review by CanadaHonk — CHANGES_REQUESTED** [review]
Could you use the `lib` directory instead of a new `utils`?

**Comment by cijiugechu** [comment]
> Could you use the `lib` directory instead of a new `utils`?

yes 😀

**Review by CanadaHonk — CHANGES_REQUESTED** [review]
Got a duplicate copy of `index.js` in `lib` by mistake haha

**Review by CanadaHonk — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
