### PR TITLE
feat: eslint

### PR DESCRIPTION
**Pull request by ThaUnknown**
this defines a fairly strict eslint config based on standard, also linted all the code using the config

this config is immensely opinionated, so alternatives are welcome, but an eslint configs are a must on FOSS project

### CODE REVIEW

**Comment by CanadaHonk** [comment]
The eslint config goes against existing code, it shouldn't.

**Comment by ThaUnknown** [comment]
I'm not willing to configure some 200 eslint rules by hand to match this style, either provide the eslint config you used or you'll have to change the style

**Comment by CanadaHonk** [comment]
I don't use a eslint config and it currently isn't needed so I'll close the PR.

**Comment by ThaUnknown** [comment]
tbh if you want to accept community PR's for a project of this scale not having an eslint config is a pitfall, you'll end up with as many code styles as you have contributors

**Comment by CanadaHonk** [comment]
> currently

**Comment by ThaUnknown** [comment]
> > currently

and the later you do it, the worse it will get to manage

**Pull request closed without merging**
